### ISSUE TITLE
Direct link to quickstarts

### ISSUE THREAD

**Issue by loopDelicious** [loopDelicious/pmquickstarts#37]
Cannot link to specific quickstarts. e.g. `https://quickstarts.postman.com/guide/php-symfony-API/index.html?index=..%2F..index#0` goes to 404.

Investigate if there is a more elegant solution to link to a specific quickstart.

**Comment by Gbahdeyboh** [comment]
@loopDelicious Copying and pasting the URL in my browser works here. It also worked for other quickstarts.

**Comment by loopDelicious** [comment]
@mjgutermuth can you confirm the issue with direct links still persists? in the guest blog post?

@Gbahdeyboh I clicked previously and went to 404. And now it resolves to the correct module. Can you confirm this behavior is not due to a site outage? I wasn't deploying at the time.

**Comment by Gbahdeyboh** [comment]
It is possible it was a site outage. I'll have a look and see if I can replicate the issue.

**Comment by loopDelicious** [comment]
@Gbahdeyboh all the previous links with underscores are broken links, now that it's been updated to dashes. Is there a way to set up redirects for the previous 25 or so modules, so that we don't need to update all existing links?

**Comment by Gbahdeyboh** [comment]
Yes, that should be possible. I'll have a look.

**Comment by loopDelicious** [comment]
@Gbahdeyboh 

- instead of generating the front-matter `id` as `PMGUIDE-NAME`, can you update it to be the hyphenated name created in the previous step? For example, if I run `npm run template kubernetes-tutorial`, can the `id` be `kubernetes-tutorial` in the new template? I believe it was previously set up like that (with underscores).
- if it doesn't mess anything up, can you update the module names from underscores to hyphens so new contributors aren't confused by the difference?

**Comment by Gbahdeyboh** [comment]
So I made a  PR to fix this [here](https://github.com/loopDelicious/pmquickstarts/pull/44) @loopDelicious
